// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgZionAhQNjib60IT3eCVFt2wma9Frs9Q',
    appId: '1:867292639067:web:ac3064d63160fa3790747e',
    messagingSenderId: '867292639067',
    projectId: 'thryv-e1366',
    authDomain: 'thryv-e1366.firebaseapp.com',
    storageBucket: 'thryv-e1366.appspot.com',
    measurementId: 'G-28K86VX2WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6vUm5aexttnth5iDHYb4KUu3cA6bYdU',
    appId: '1:867292639067:android:32d3a24bae88d2d690747e',
    messagingSenderId: '867292639067',
    projectId: 'thryv-e1366',
    storageBucket: 'thryv-e1366.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJO-oqkMu0nWO-lGiMxyxxufmT_mfD-c',
    appId: '1:867292639067:ios:b30a09a4335544d890747e',
    messagingSenderId: '867292639067',
    projectId: 'thryv-e1366',
    storageBucket: 'thryv-e1366.appspot.com',
    iosBundleId: 'com.example.thryv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArJO-oqkMu0nWO-lGiMxyxxufmT_mfD-c',
    appId: '1:867292639067:ios:66382ba56e40142390747e',
    messagingSenderId: '867292639067',
    projectId: 'thryv-e1366',
    storageBucket: 'thryv-e1366.appspot.com',
    iosBundleId: 'com.example.thryv.RunnerTests',
  );
}
